In [2]:
#Creating Arrays
import numpy as np

# 1D array
arr1 = np.arange(1, 11)
print(arr1)

# 2D array (3x3)
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)

# 3D random array (3,5,3)
arr3 = np.random.rand(3, 5, 3)
print(arr3)

# Shapes, sizes, dtypes
print(arr1.shape, arr1.size, arr1.dtype)
print(arr2.shape, arr2.size, arr2.dtype)
print(arr3.shape, arr3.size, arr3.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[0.23534652 0.42845384 0.74865106]
  [0.31859313 0.26537631 0.17818722]
  [0.16801184 0.85827859 0.34761699]
  [0.5126251  0.82411287 0.51054515]
  [0.30106016 0.0472422  0.36821177]]

 [[0.36609358 0.06854419 0.88181318]
  [0.26666717 0.820639   0.84440794]
  [0.70515075 0.65081558 0.602093  ]
  [0.7144625  0.61273499 0.78223533]
  [0.30262421 0.75271814 0.73767669]]

 [[0.7990197  0.66834546 0.32037751]
  [0.78367707 0.73347232 0.09711186]
  [0.49683453 0.97168434 0.38719604]
  [0.03924437 0.59513958 0.04283769]
  [0.45038679 0.52938215 0.83698396]]]
(10,) 10 int32
(3, 3) 9 int32
(3, 5, 3) 45 float64


In [4]:
#Array Indexing and Slicing
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(data[:3])          # First three elements
print(data[::2])         # Every alternate element
print(data[::-1])        # Reverse


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [7]:
# Mathematical Ops
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("A:", A)
print("B:", B)

print("Add:", A + B)
print("Subtract:", A - B)
print("Multiply:", A * B)
print("Divide:", A / B)

print("Dot Product:", np.dot(A, B))

print("A Mean:", np.mean(A))
print("A Median:", np.median(A))
print("A Std:", np.std(A))
print("A Var:", np.var(A))

print("B Max:", np.max(B), "at index", np.argmax(B))
print("B Min:", np.min(B), "at index", np.argmin(B))


A: [15  8 11  1  4]
B: [19 17  3 17 14]
Add: [34 25 14 18 18]
Subtract: [ -4  -9   8 -16 -10]
Multiply: [285 136  33  17  56]
Divide: [0.78947368 0.47058824 3.66666667 0.05882353 0.28571429]
Dot Product: 527
A Mean: 7.8
A Median: 8.0
A Std: 4.955804677345546
A Var: 24.56
B Max: 19 at index 0
B Min: 3 at index 2


In [8]:
# Reshaping And Trnasposing
arr = np.arange(1, 13)

arr2d = arr.reshape(4, 3)
print(arr2d)

arr3d = arr.reshape(2, 2, 3)
print(arr3d)

transposed = arr2d.T
print(transposed)
print("Transposed shape:", transposed.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transposed shape: (3, 4)


In [9]:
# Boolean masking and filtering 
arr = np.random.randint(10, 51, 15)
print("Array:", arr)

print("Elements >25:", arr[arr > 25])

arr[arr < 30] = 0
print("After replacing <30 with 0:", arr)

print("Count divisible by 5:", np.sum(arr % 5 == 0))


Array: [43 46 39 26 26 49 19 15 28 12 44 11 12 13 35]
Elements >25: [43 46 39 26 26 49 28 44 35]
After replacing <30 with 0: [43 46 39  0  0 49  0  0  0  0 44  0  0  0 35]
Count divisible by 5: 10


In [ ]:
# Working with built in functions
print(np.linspace(0, 1, 10))

print(np.eye(4))

arr = np.random.randint(1, 101, 20)
arr.sort()
print("Sorted:", arr)
print("5 largest:", arr[-5:])
